name: Node CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.DODAO_ONBOARDING_SCHEMAS_ACCESS_TOKEN }}
          persist-credentials: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, lint
        run: |
          yarn
          yarn run build
          yarn run lint
        env:
          NODE_OPTIONS: --max-old-space-size=4096
